\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Resampling Method 2. Bootstrap}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

Sunah Park

This markdown file is created by Sunah Park for extended lab exercises
in the book \emph{An Introduction to Statistical Learning with
Applications in R}
\href{https://www-bcf.usc.edu/~gareth/ISL/ISLR\%20First\%20Printing.pdf}{(ISLR)}.

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\subsubsection{Setup for code chunks}\label{setup-for-code-chunks}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rm}\NormalTok{(}\DataTypeTok{list=}\KeywordTok{ls}\NormalTok{())}
\CommentTok{# default r markdown global options in document}
\NormalTok{knitr}\OperatorTok{::}\NormalTok{opts_chunk}\OperatorTok{$}\KeywordTok{set}\NormalTok{(}
\NormalTok{   ########## Text results ##########}
    \DataTypeTok{echo=}\OtherTok{TRUE}\NormalTok{, }
    \DataTypeTok{warning=}\OtherTok{FALSE}\NormalTok{, }\CommentTok{# to preserve warnings in the output }
    \DataTypeTok{error=}\OtherTok{FALSE}\NormalTok{, }\CommentTok{# to preserve errors in the output}
    \DataTypeTok{message=}\OtherTok{FALSE}\NormalTok{, }\CommentTok{# to preserve messages}
    \DataTypeTok{strip.white=}\OtherTok{TRUE}\NormalTok{, }\CommentTok{# to remove the white lines in the beginning or end of a source chunk in the output }

\NormalTok{    ########## Cache ##########}
    \DataTypeTok{cache=}\OtherTok{TRUE}\NormalTok{,}
   
\NormalTok{    ########## Plots ##########}
    \DataTypeTok{fig.path=}\StringTok{""}\NormalTok{, }\CommentTok{# prefix to be used for figure filenames}
    \DataTypeTok{fig.width=}\DecValTok{8}\NormalTok{,}
    \DataTypeTok{fig.height=}\DecValTok{6}\NormalTok{,}
    \DataTypeTok{dpi=}\DecValTok{200}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ISLR)}
\KeywordTok{library}\NormalTok{(boot) }\CommentTok{# function boot()}
\KeywordTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(Portfolio) }\CommentTok{# Stock market data from ISLR library}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        X                  Y           
##  Min.   :-2.43276   Min.   :-2.72528  
##  1st Qu.:-0.88847   1st Qu.:-0.88572  
##  Median :-0.26889   Median :-0.22871  
##  Mean   :-0.07713   Mean   :-0.09694  
##  3rd Qu.: 0.55809   3rd Qu.: 0.80671  
##  Max.   : 2.46034   Max.   : 2.56599
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(Portfolio,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            X          Y
## 1 -0.8952509 -0.2349235
## 2 -1.5624543 -0.8851760
## 3 -0.4170899  0.2718880
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Portfolio<-}\KeywordTok{na.omit}\NormalTok{(Portfolio)}
\KeywordTok{dim}\NormalTok{(Portfolio)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 100   2
\end{verbatim}

\subsubsection{alpha calculation}\label{alpha-calculation}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha<-}\ControlFlowTok{function}\NormalTok{(data, index) \{}
\NormalTok{    x<-data}\OperatorTok{$}\NormalTok{X[index]}
\NormalTok{    y<-data}\OperatorTok{$}\NormalTok{Y[index]}
\NormalTok{    alpha<-(}\KeywordTok{var}\NormalTok{(y)}\OperatorTok{-}\KeywordTok{cov}\NormalTok{(x,y))}\OperatorTok{/}\NormalTok{(}\KeywordTok{var}\NormalTok{(x)}\OperatorTok{+}\KeywordTok{var}\NormalTok{(y)}\OperatorTok{-}\DecValTok{2}\OperatorTok{*}\KeywordTok{cov}\NormalTok{(x,y))}
    \KeywordTok{return}\NormalTok{(alpha)}
\NormalTok{\}}

\KeywordTok{alpha}\NormalTok{(Portfolio, }\DecValTok{1}\OperatorTok{:}\DecValTok{100}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5758321
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\KeywordTok{alpha}\NormalTok{(Portfolio, }\KeywordTok{sample}\NormalTok{(}\DecValTok{100}\NormalTok{,}\DecValTok{100}\NormalTok{, }\DataTypeTok{replace=}\OtherTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5963833
\end{verbatim}

\subsubsection{boot() function}\label{boot-function}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\KeywordTok{boot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{Portfolio, }\DataTypeTok{statistic=}\NormalTok{alpha, }\DataTypeTok{R=}\DecValTok{1000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = Portfolio, statistic = alpha, R = 1000)
## 
## 
## Bootstrap Statistics :
##      original       bias    std. error
## t1* 0.5758321 6.936399e-05  0.08868935
\end{verbatim}

boot() generates R bootstrap replicate of a statistic applied to data.
The bootstrap sample is the same size as the original dataset. As a
result, some samples will be represented multiple times in the bootstrap
sample while others will not be selected at all. \textbf{statistic} is a
function which when applied to data returns a vector containing the
statistics of interest. R is the number of bootstrap replicates. The
final output shows that using the original data, alpha=0.5758 and that
the bootstrap estimate for standard error is 0.0886.

\subsubsection{Estimating the Accuracy of a Linear Regression
Model}\label{estimating-the-accuracy-of-a-linear-regression-model}

The bootstrap approach can be used to assess the variability of the
coefficient estimates and predictions from a statistical learning
method. Here we use the bootstrap approach in order to assess the
variability of the estimates for betas, the intercept and slope terms
for the linear regression model that uses horsepower to predict pmg in
the Auto data set. We compare the estimates obtained using the
bootstrap.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\NormalTok{boot.fn<-}\ControlFlowTok{function}\NormalTok{(data, index) \{}
    \KeywordTok{return}\NormalTok{(}\KeywordTok{coef}\NormalTok{(}\KeywordTok{lm}\NormalTok{(mpg}\OperatorTok{~}\NormalTok{horsepower, }\DataTypeTok{data=}\NormalTok{data, }\DataTypeTok{subset=}\NormalTok{index)))}
\NormalTok{\}}

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\KeywordTok{boot.fn}\NormalTok{(}\DataTypeTok{data=}\NormalTok{Auto,}\KeywordTok{sample}\NormalTok{(}\DecValTok{392}\NormalTok{,}\DecValTok{392}\NormalTok{,}\DataTypeTok{replace=}\OtherTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)  horsepower 
##  38.7387134  -0.1481952
\end{verbatim}

The boot.fn() function is used in order to create bootstrap estimates
for the intercept and slope terms by randomly sampling among the
observations with replacement.

We now compute the standard errors of 1000 bootstrap estimates for the
intercept and slope terms.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\KeywordTok{boot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{Auto, }\DataTypeTok{statistic=}\NormalTok{boot.fn, }\DataTypeTok{R=}\DecValTok{1000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = Auto, statistic = boot.fn, R = 1000)
## 
## 
## Bootstrap Statistics :
##       original        bias    std. error
## t1* 39.9358610  0.0269563085 0.859851825
## t2* -0.1578447 -0.0002906457 0.007402954
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(}\KeywordTok{lm}\NormalTok{(mpg}\OperatorTok{~}\NormalTok{horsepower,}\DataTypeTok{data=}\NormalTok{Auto))}\OperatorTok{$}\NormalTok{coef}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Estimate  Std. Error   t value      Pr(>|t|)
## (Intercept) 39.9358610 0.717498656  55.65984 1.220362e-187
## horsepower  -0.1578447 0.006445501 -24.48914  7.031989e-81
\end{verbatim}

This indicates that the bootstrap estimate for SE(beta0) is 0.86, and
that the bootstrap estimate for SE(beta1) is 0.0074. The standard error
estimates for beta0 and beta1 from the linear model fit is 0.717 and
0.006, respectively. There are somewhat different from the estimates
obtained using the bootstrap.

We compute the bootstrap standard error estimates and the standard
linear regression estimates that result from fitting the quadratic
model.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\NormalTok{boot.fn<-}\ControlFlowTok{function}\NormalTok{(data, index) \{}
    \KeywordTok{return}\NormalTok{(}\KeywordTok{coef}\NormalTok{(}\KeywordTok{lm}\NormalTok{(mpg}\OperatorTok{~}\NormalTok{horsepower}\OperatorTok{+}\KeywordTok{I}\NormalTok{(horsepower}\OperatorTok{^}\DecValTok{2}\NormalTok{), }\DataTypeTok{data=}\NormalTok{data, }\DataTypeTok{subset=}\NormalTok{index)))}
\NormalTok{\}}

\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\KeywordTok{boot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{Auto, }\DataTypeTok{statistic=}\NormalTok{boot.fn, }\DataTypeTok{R=}\DecValTok{1000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = Auto, statistic = boot.fn, R = 1000)
## 
## 
## Bootstrap Statistics :
##         original        bias     std. error
## t1* 56.900099702  6.098115e-03 2.0944855842
## t2* -0.466189630 -1.777108e-04 0.0334123802
## t3*  0.001230536  1.324315e-06 0.0001208339
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(}\KeywordTok{lm}\NormalTok{(mpg}\OperatorTok{~}\NormalTok{horsepower}\OperatorTok{+}\KeywordTok{I}\NormalTok{(horsepower}\OperatorTok{^}\DecValTok{2}\NormalTok{), }\DataTypeTok{data=}\NormalTok{Auto))}\OperatorTok{$}\NormalTok{coef}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                     Estimate   Std. Error   t value      Pr(>|t|)
## (Intercept)     56.900099702 1.8004268063  31.60367 1.740911e-109
## horsepower      -0.466189630 0.0311246171 -14.97816  2.289429e-40
## I(horsepower^2)  0.001230536 0.0001220759  10.08009  2.196340e-21
\end{verbatim}

Since this model provides a good fit to the data, there is now a better
correspondence between the bootstrap estimates and the standard
estimates.


\end{document}
